@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Dec 13 10:27:37 +0800 2021
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim CPU_tb_time_synth -key {Post-Synthesis:sim_1:Timing:CPU_tb} -tclbatch CPU_tb.tcl -view D:/MIPS32_CPU/CPU/CPU.sim/sim_1/behav/xsim/CPU_tb_behav.wcfg -log simulate.log"
call xsim  CPU_tb_time_synth -key {Post-Synthesis:sim_1:Timing:CPU_tb} -tclbatch CPU_tb.tcl -view D:/MIPS32_CPU/CPU/CPU.sim/sim_1/behav/xsim/CPU_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
